### PR TITLE
optimized the filesystem line to do relative seeks.

### PR DESCRIPTION
**Pull request by yjv**
should make sequential reads not get slower and slower as they go deeper into the file

### CODE REVIEW

**Comment by yjv** [comment]
@clphillips this should fix #10

**Comment by yjv** [comment]
@clphillips im having a hard time reproducing the increasing slowness issue to see if this really helps it. would you be able to post an example script and file where this can be demonstrated so i can compare?

thanks

**Comment by clphillips** [comment]
I don't have a file I can post, but like I said in #10 it was 89 bytes per line in a 1.4 GB file. I believe there was about 10 fields per line, though I'm sure that doesn't matter.

Since where blocks of files are stored on disk is OS/hardware dependent, I can't say for certain that you'd only need a test file with X lines, but I think if you create a test file with 25,000 lines, 89 bytes per line, you should have a sufficiently large file that won't be stored contiguously on disk.

If not, I might have some time next week where I could put this commit to the test on that 1.4 GB file..

**Comment by yjv** [comment]
Ok thanks. I generated a 5gb file with about 5000000 lines all 100 chars across and wasnt seeing it. hopefully youll be able to see it.

**Pull request merged**
